### ISSUE TITLE
Pull Request Policy

### ISSUE THREAD

**Issue by jshlbrd** [hashicorp-forge/grove#18]
Hi folks, this is a nice project, and similar to something we've run internally for a few years. I noticed that the project cannot accept external PRs for connectors and plugins -- does that apply to all code?

**Comment by hcpadkins** [comment]
Hey there,

Thank you for raising this issue. Contributions into the Grove project are definitely welcome!

However, there are a few caveats with connectors and certain plugins:

Our concern around external connector contributions stems from our inability to validate or keep up-to-date any connectors for products which we do not have access to ourselves. This is especially difficult for products which require subscriptions, or only make audit logs available under certain subscription levels.

That said, we can be a little more flexible with plugins such as backends which use open source products, as we can more easily validate these. However, similar to connectors, backends which require access to licensed software or services which we do not access to would be more of a challenge :) 

Thank you again for your issue, and please let me know if you have further questions, we'd be happy to discuss further!

**Comment by jshlbrd** [comment]
Thanks for clarifying @hcpadkins!

**Comment by hcpadkins** [comment]
Hey there 👋 

Just as an update, we've amended our pull-request and contribution policy as we prepare for the first official v1.0.0 release:

```
Grove may be able to accept pull-requests for merging new connectors into Grove.
However, the Grove project may not be able to accept pull-requests for connectors which
require licensing or paid subscription access.

If you are unsure, please open a Github issue and we'll let you know!
```

```
Grove may be able to accept pull-requests for plugins which add or improve support
for new backends and processors. However, the Grove project may not be able to accept
plugins which have a significant number of required dependencies, or are for non-free
backends which we are unable to test or maintain (generally due to lack of licensing,
or access to the software).

If you are unsure, please open a Github issue and we'll let you know!
```
