### ISSUE TITLE
Grove Installation Issue

### ISSUE THREAD

**Issue by bojiang1990** [hashicorp-forge/grove#19]
Hi there, I'm following the quick-start doc to install grove. The pip install grove works properly, I can find the path, I can also find grove in my docker container. However, when I use the command line "grove", it shows "the command line not found". Is there any issue about the package? Or anything I need pay attention to that not included in the document? Thanks

**Comment by hcpadkins** [comment]
Hey @bojiang1990,

Thank you for raising this issue!

Currently, the current release candidate version of Grove has only been published to PyPI as a pre-release. We will be cutting our first real release shortly, but we have a few pieces of feedback we're looking to address first.

As a result, the version of Grove installed via `pip install grove` is likely version `0.0.0` - as by default pip will only install "stable" versions. You can instead ask PyPi to install the published pre-release version using `pip install --pre grove`, which should allow you to start using Grove in its pre-release form.

Please let me know if this resolves your issue.

**Comment by bojiang1990** [comment]
Thanks for the information, I can play with it now. Looking forward to your first release.

**Comment by bojiang1990** [comment]
I need some guidance on the usage of grove: for the following example, 

cat > grove/config/heartbeat.json << EOF
{
    "name": "EC0FFEE1",
    "identity": "EC0FFEE1",
    "connector": "slack_audit_logs",
    "key": "xoxb-..."
}
EOF

What do "name", "identity", "key" stand for? I suppose one of these should be user name, and the other two are passwords and profile name?
